# Generated by Django 5.0.1 on 2024-02-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_answer_next_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Текст вопроса'),
        ),
    ]
