# Generated by Django 5.0.1 on 2024-02-02 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_question_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Опрос пользователя',
                'verbose_name_plural': 'Опросы пользователей',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_first',
        ),
        migrations.AddField(
            model_name='survey',
            name='first_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_surveys_questions', to='survey.question', verbose_name='Первый вопрос'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='unique_user_answer'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='last_answer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.answer'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='survey.survey', verbose_name='Опрос'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='survey',
            name='respondents',
            field=models.ManyToManyField(through='survey.UserSurvey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usersurvey',
            constraint=models.UniqueConstraint(fields=('user', 'survey'), name='unique_user_survey'),
        ),
    ]
