# Generated by Django 5.0.1 on 2024-02-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_usersurvey_remove_question_is_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='last_answer',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='last_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
    ]
