# Generated by Django 5.0.1 on 2024-02-02 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_usersurvey_last_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='last_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question', verbose_name='Текущий вопрос'),
        ),
    ]
