# Generated by Django 5.0.1 on 2024-02-02 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_usersurvey_last_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='last_question',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='last_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.answer', verbose_name='Последний ответ'),
        ),
    ]
